# Generated by Django 5.2.15 on 2026-07-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LEAVE_APPLIED', 'Leave Applied'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_ESCALATED', 'Leave Escalated'), ('LEAVE_CANCELLATION', 'Leave Cancellation'), ('REGULARIZATION_APPLIED', 'Regularization Applied'), ('REGULARIZATION_APPROVED', 'Regularization Approved'), ('REGULARIZATION_REJECTED', 'Regularization Rejected')], max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
