# Generated by Django 5.2.15 on 2026-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'company holidays',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='weekly_off_days',
            field=models.JSONField(default=list, help_text='Weekday numbers (Monday=0) that are weekly offs. Default Sat/Sun: [5, 6]'),
        ),
    ]
