# Generated by Django 5.2.15 on 2026-07-02 19:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_companyholiday_companysettings_weekly_off_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='company_start_time',
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyholiday',
            name='holiday_type',
            field=models.CharField(choices=[('COMPANY_HOLIDAY', 'Company Holiday'), ('OPTIONAL_HOLIDAY', 'Optional Holiday'), ('FESTIVAL', 'Festival'), ('NATIONAL_HOLIDAY', 'National Holiday')], default='COMPANY_HOLIDAY', max_length=30),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(default='Antro PAI Technology Pvt Ltd', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='financial_year_start_month',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='full_day_minimum_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='half_day_minimum_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='leave_joining_cutoff_day',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='office_end_time',
            field=models.TimeField(default='18:30:00'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='office_start_time',
            field=models.TimeField(default='09:30:00'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='weekly_off_days',
            field=models.JSONField(default=list, help_text='Weekday numbers (Monday=0) that are weekly offs.'),
        ),
    ]
