# Generated by Django 5.2.15 on 2026-07-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_remove_companysettings_company_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholiday',
            name='base_holiday_type',
            field=models.CharField(choices=[('COMPANY_HOLIDAY', 'Company Holiday'), ('OPTIONAL_HOLIDAY', 'Optional Holiday'), ('FESTIVAL', 'Festival'), ('NATIONAL_HOLIDAY', 'National Holiday')], default='COMPANY_HOLIDAY', help_text='Original type restored when optional holiday is turned off.', max_length=30),
        ),
    ]
