# Generated by Django 5.2.15 on 2026-07-02 14:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('OFFICE', 'Office'), ('WORK_FROM_HOME', 'Work From Home'), ('CLIENT_LOCATION', 'Client Location')], default='OFFICE', max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday')], default='ABSENT', max_length=20)),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_per_day')],
            },
        ),
    ]
