# Generated by Django 5.2.15 on 2026-07-02 17:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_internship_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual'), ('SICK', 'Sick'), ('EMERGENCY', 'Emergency'), ('PLANNED', 'Planned'), ('UNPAID', 'Unpaid')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_working_days', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('half_day', models.BooleanField(default=False)),
                ('half_day_session', models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CANCELLATION_REQUESTED', 'Cancellation Requested')], default='PENDING', max_length=30)),
                ('approval_level', models.CharField(choices=[('MANAGER', 'Manager'), ('HR', 'HR Admin')], default='MANAGER', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('escalated_to_hr', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('is_backdated', models.BooleanField(default=False)),
                ('is_special_approval_required', models.BooleanField(default=False)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('paid_leave_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('paid_leave_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('paid_leave_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
            ],
            options={
                'ordering': ('-year', 'employee__employee_code'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'year'), name='unique_leave_balance_per_employee_year')],
            },
        ),
    ]
