# Generated by Django 6.0.6 on 2026-07-07 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_merge_20260707_1512'),
        ('offer_letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(choices=[('Sales & Marketing', 'Sales & Marketing'), ('HR', 'HR'), ('Technology', 'Technology'), ('Operations', 'Operations'), ('Management', 'Management'), ('Finance', 'Finance'), ('Admin', 'Admin')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERN', 'Intern'), ('CONTRACT', 'Contract'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20)),
                ('work_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INVITED', 'Invited'), ('PROFILE_PENDING', 'Profile Pending'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CORRECTION_REQUIRED', 'Rejected / Correction Required')], default='NOT_STARTED', max_length=30)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('education_details', models.JSONField(blank=True, default=list)),
                ('employment_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='employees.employee')),
                ('offer_letter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_record', to='offer_letters.offerletter')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_reports', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('RESUME', 'Resume'), ('PHOTO', 'Photo'), ('EDUCATION_CERTIFICATE', 'Education Certificate'), ('EXPERIENCE_RELIVING', 'Experience / Relieving Letter')], max_length=40)),
                ('file', models.FileField(upload_to='onboarding/documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboardingrecord')),
            ],
            options={
                'ordering': ('document_type', '-uploaded_at'),
                'unique_together': {('onboarding', 'document_type')},
            },
        ),
    ]
