# Generated by Django 5.2.15 on 2026-07-02 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_internship_end_date_and_more'),
        ('payroll', '0002_payrollrun_employeepayrolldraft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10)),
                ('aadhaar_last_four', models.CharField(max_length=4)),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_holder_name', models.CharField(max_length=120)),
                ('uan_number', models.CharField(blank=True, max_length=20)),
                ('pf_number', models.CharField(blank=True, max_length=30)),
                ('esi_number', models.CharField(blank=True, max_length=30)),
                ('tax_regime', models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime'), ('NOT_DECLARED', 'Not Declared')], default='NOT_DECLARED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_profile', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee__employee_code'],
            },
        ),
    ]
