# Generated by Django 5.2.15 on 2026-07-02 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeepayrollprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='annual_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable — excluded employee'), ('APPLICABLE_EXISTING_UAN', 'Applicable — employee already has PF/UAN'), ('APPLICABLE_COMPANY_POLICY', 'Applicable — company policy'), ('APPLICABLE_STATUTORY', 'Applicable — statutory requirement'), ('VOLUNTARY_PF', 'Voluntary PF')], default='NOT_APPLICABLE', max_length=40),
        ),
    ]
