# Generated by Django 5.2.15 on 2026-07-02 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salarystructure_annual_ctc_salarystructure_pf_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='adjustment_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='hold_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='incentive_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='reimbursement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_drafts_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayrolldraft',
            name='status',
            field=models.CharField(choices=[('MISSING_SALARY_STRUCTURE', 'Missing Salary Structure'), ('MISSING_PAYROLL_PROFILE', 'Missing Payroll Profile'), ('READY', 'Ready')], default='READY', max_length=40),
        ),
    ]
