# Generated by Django 6.0.6 on 2026-07-07 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_merge_20260707_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(choices=[('Sales & Marketing', 'Sales & Marketing'), ('HR', 'HR'), ('Technology', 'Technology'), ('Operations', 'Operations'), ('Management', 'Management'), ('Finance', 'Finance'), ('Admin', 'Admin')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('reporting_manager_name', models.CharField(blank=True, max_length=200)),
                ('work_location', models.CharField(blank=True, max_length=150)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERN', 'Intern'), ('CONTRACT', 'Contract'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20)),
                ('offered_ctc', models.TextField(help_text='Compensation summary for the offer document only.')),
                ('offer_valid_till', models.DateField()),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('acceptance_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_document_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offer_letters', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_letters_as_manager', to='employees.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
