# Generated by Django 5.2.15 on 2026-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_internship_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Sales & Marketing', 'Sales & Marketing'), ('HR', 'HR'), ('Technology', 'Technology'), ('Operations', 'Operations'), ('Management', 'Management'), ('Finance', 'Finance'), ('Admin', 'Admin')], max_length=100),
        ),
    ]
