# Generated by Django 6.0.6 on 2026-07-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_backfill_blank_employee_codes'),
        ('employees', '0003_employee_department_choices'),
    ]

    operations = [
    ]
