# Generated by Django 5.2.15 on 2026-07-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LEAVE_POLICY', 'Leave Policy'), ('ATTENDANCE_POLICY', 'Attendance Policy'), ('WFH_POLICY', 'Work From Home Policy'), ('CODE_OF_CONDUCT', 'Code of Conduct'), ('DATA_SECURITY', 'Data Security Policy'), ('ASSET_USAGE', 'Asset Usage Policy'), ('PAYROLL_POLICY', 'Salary/Payroll Policy'), ('EXIT_POLICY', 'Exit Policy'), ('PROBATION_POLICY', 'Probation Policy'), ('ANTI_HARASSMENT', 'Anti-Harassment Policy'), ('OTHER', 'Other')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('policy_file', models.FileField(upload_to='policies/')),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ('-effective_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged')], default='PENDING', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='policies.policy')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('policy', 'employee', 'policy_version'), name='unique_policy_ack_per_employee_version')],
            },
        ),
    ]
