# Generated by Django 5.2.15 on 2026-07-06 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=150)),
                ('service_fit', models.CharField(choices=[('ANTRO_WORKFORCE', 'Antro Workforce Services'), ('WODENA_TECHNOLOGY', 'Wodena Technology Services'), ('IGOLO_INTERIOR', 'Igolo Interior Services'), ('TECHNOLOGY_SOLUTIONS', 'Technology Solutions')], max_length=40)),
                ('current_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required'), ('MEETING_BOOKED', 'Meeting Booked'), ('PROPOSAL_SENT', 'Proposal Sent'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed')], default='NEW', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
