# Generated by Django 5.2 on 2026-07-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadimporthistory_error_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_lead_activities',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='edited_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='edited_lead_activities',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='not_counted_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SalesRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(
                    choices=[
                        ('DUPLICATE_ACTIVITY', 'Duplicate Activity'),
                        ('SAME_REMARK_REPEATED', 'Same Remark Repeated'),
                        ('SAME_STATUS_NO_CHANGE', 'Same Status No Change'),
                        ('LOW_LEAD_QUALITY', 'Low Lead Quality'),
                        ('LEADS_WITHOUT_DECISION_MAKERS', 'Leads Without Decision Makers'),
                        ('KPI_MISSED', 'KPI Missed'),
                        ('CHECKOUT_REASON_SUBMITTED', 'Checkout Reason Submitted'),
                        ('OVERDUE_FOLLOWUP', 'Overdue Follow-up'),
                        ('BULK_UPLOAD_DUPLICATES', 'Bulk Upload Duplicates'),
                        ('ACTIVITY_EDITED', 'Activity Edited'),
                        ('ACTIVITY_DELETED', 'Activity Deleted'),
                    ],
                    max_length=40,
                )),
                ('severity', models.CharField(
                    choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')],
                    default='MEDIUM',
                    max_length=10,
                )),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sales_risk_events',
                    to='leads.leadactivity',
                )),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sales_risk_events',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('lead', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sales_risk_events',
                    to='leads.lead',
                )),
                ('resolved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_sales_risk_events',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
